#!/usr/bin/bash

export PATH=$PATH:/home/ce/zk/playground/circom-101/genesis_cpp/

echo "Installing cpp helper libs........................."

##### nlohmann-json3-dev #########
sudo apt update
sudo apt install nlohmann-json3-dev

##### libgmp-dev #########
sudo apt update
sudo apt install libgmp-dev

##### nasm #########
sudo apt-get update
sudo apt -y install nasm

echo "Installation complete!!"
